-- Run this in Supabase SQL Editor

-- Altering existing table likely requires 'ALTER TABLE' in production, 
-- but for this script we provide the full CREATE definition for fresh starts
-- OR separate ALTER statements.

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL,
    phone_number TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL, 
    residence_type TEXT NOT NULL, 
    birth_place TEXT,    -- New
    birth_date TEXT,     -- New (Keeping as TEXT to match CSV format dd/mm/yyyy easily, or we can parse to DATE)
    university TEXT,     -- New
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS claims (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id),
    claimed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE claims ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public Read Users" ON users FOR SELECT USING (true);
CREATE POLICY "Public Insert Users" ON users FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Read Claims" ON claims FOR SELECT USING (true);
CREATE POLICY "Public Insert Claims" ON claims FOR INSERT WITH CHECK (true);
